version: '3.4'

services:
  apidb:
    container_name: apidb
    restart: always
    environment:
      SA_PASSWORD: "Pass@word"
      ACCEPT_EULA: "Y"
    ports:
      - "1437:1433"
    
  realestate.api:
    container_name: realestate.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80      
      - "ConnectionStrings:RealEstateAPIConnectionString=Server=apidb;Database=RealEstateDB;User Id=sa;Password=Pass@word;Encrypt=false" 
      - "JWT:Key=ZdYM000OLlMQG6VVVp1OH7Xarp7gHuw1qvUC5dcGt3SNM"
      - "JWT:Issuer=http://localhost:8000/"
      - "JWT:Audience=http://localhost:8000/"
    volumes:
      - ~/.aspnet/https:/https:ro
    restart: on-failure
    ports:
    - "8000:80"  
    - "8300:443"  
    
    depends_on:
      - apidb 