version: '3.4'

services:
  apidb:
    image: mcr.microsoft.com/mssql/server:2019-latest
  
  realestate.api:
    image: ${DOCKER_REGISTRY-}realestateapi
    build:
      context: .
      dockerfile: src/API/RealEstateAPI/Dockerfile
     